#Downloaded from olback.net
alias update='apt update && apt upgrade -y && apt autoremove -y'
alias c='clear'
alias pag='ps aux | grep'
alias agi='apt update && apt-get install-y'
alias s='sudo -i'
alias www='cd /var/www && ls'
eval $(thefuck --alias fuck)
alias www-data='chown www-data:www-data /var/www/ -R'
