[package]
name = "olback_net"
version = "0.1.0"
authors = ["olback <web@olback.net>"]

[dependencies]
rocket = "0.3.9"
rocket_codegen = "0.3.9"
rocket_contrib = "0.3.9"
lettre = "0.8"
lettre_email = "0.8"
