[package]
name = "olback_net"
version = "4.0.0"
authors = ["olback <web@olback.net>"]

[dependencies]
rocket = "0.4.2"
rocket_codegen = "0.4.2"
rocket_contrib = { version = "0.4.2", default-features = false, features = ["handlebars_templates"] }
lettre = "0.9.2"
lettre_email = "0.9.2"
serde = "1.0.55"
serde_derive = "1.0.55"
mailchecker = "3.2.5"
colored = "1.6"
