[package]
name = "olback_net"
version = "3.0.0"
authors = ["olback <web@olback.net>"]

[dependencies]
rocket = "0.3.10"
rocket_codegen = "0.3.10"
rocket_contrib = { version = "0.3.10", default-features = false, features = ["handlebars_templates"] }
lettre = "0.8.2"
lettre_email = "0.8.2"
serde = "1.0.55"
serde_derive = "1.0.55"
mailchecker = "3.2.5"
