# Mail Server Conf
host = "" # Mail server hostname
port = 587 # SMPT Port 25, 465, 587
username = "" # Mail user name
password = "" # Mail password

# Mail conf
from = "" # From address
to = "" # To address
name = "" # From name
site = "" # Site domain
