# Mail Conf
[mail]
host = "" # Mail server hostname
port = 587 # SMPT Port 25, 465, 587
username = "" # Mail user name
password = "" # Mail password
from = "" # From address
to = ""
name = "" # From name
site = "" # Site domain

# Birthday
[birthday]
year = 0000
month = 1
day = 1

[circle_ci]
username = "olback"
repo_name = "olback.net"
branch = "4.0"
token = ""
blob = "home/circleci/project/target/release/olback_net"
checksum = "home/circleci/project/target/release/olback_net_checksum"
