version: 2

jobs:
  build:
    docker:
      - image: abronan/rust-circleci:latest
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Set rustup toolchain
          command: rustup override set nightly
      - run:
          name: Rustup update
          command: rustup update
      - run:
          name: Cargo update
          command: cargo update
      - run:
          name: Copy config
          command: cp src/sample.conf.rs src/conf.rs
      - run:
          name: Build
          command: cargo build --release
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
