
if ( typeof(Yesup) == "undefined" || ! Yesup.hasNetwork("clicksor") ) {
    document.write("<img src=\"https://tr1.myroitracking.com/newServing/tracking_id.php?d=b.yu0123456.com&r=http%3A%2F%2Fb.yu0123456.com%2FnewServing%2Ftracking_id.php%3Fb%3D1%26&gtruid=1\" width=\"1\" height=\"1\" />");
}


private_label_prefix = "clicksor";
clicksor_company_name = "Clicksor";
clicksor_static_host = "pub.clicksor.net";
clicksor_service = "b.yu0123456.com";
clicksor_image_base_url = "https://pub.clicksor.net/newServing/img/";
clicksor_search_base_url = "https://b.yu0123456.com/newServing/yesupSearch/web.php?q=";

clicksor_banner_panel = false;

clicksor_adhere_url = "https://signup.clicksor.com/advertise_here.php?nid=1&srid=32362089";
clicksor_widget_title = "Clicksor Connect";
clicksor_widget_title_link = "https://www.clicksor.com/connect-widget";

clicksor_pub_host = "admin.clicksor.com/publisher";
clicksor_nid=1;
clicksor_pid=334423;
clicksor_sid=622312;
clicksor_banner_adtype=3;
clicksor_default_banner_border="#B4D0DC";
clicksor_default_banner_bg="#ECF8FF";

if ( typeof(Yesup) == "undefined" || ! Yesup.hasNetwork("clicksor") ) {
    document.write("<iframe src=\"//b.yu0123456.com/newServing/searchTrack.php?nid=1&sid=622312&random=1554886338\" width=\"1\" height=\"1\" frameborder=\"0\" scrolling=\"no\" style=\"position:absolute;z-index:9999301;\"></iframe>");
}

if ( typeof(Yesup) == "undefined" ) {
        document.write('<script type="text/javascript" src="//pub.clicksor.net/newServing/js/show.js"></script>');
    }  else {
    Yesup.Init();
}

// generated by www225 in 0 seconds
